name: Jira Ticket Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled, closed]
    branches: [main]

jobs:
  jira-check:
    if: github.event.action != 'closed'
    uses: EAO-Global-Consulting/eao-github-workflows/.github/workflows/jira-check.yml@main
    with:
      pr_title: ${{ github.event.pull_request.title }}
      jira_base_url: https://eaoglobalconsulting.atlassian.net
      project_key: DSB
      pr_labels: ${{ toJson(github.event.pull_request.labels.*.name) }}
      required_status: 'Dev Done'
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

  jira-transition:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: EAO-Global-Consulting/eao-github-workflows/.github/workflows/jira-check.yml@main
    with:
      pr_title: ${{ github.event.pull_request.title }}
      jira_base_url: https://eaoglobalconsulting.atlassian.net
      project_key: DSB
      pr_labels: ${{ toJson(github.event.pull_request.labels.*.name) }}
      required_status: 'Dev Done'
      merged: true
      transition_to: 'Done(Prod)'
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
